# Default initial positions for robot_arm's ros2_control fake system

initial_positions:
  arm_base_joint: -1.5708  # -π/2 (middle of range [-π, 0])
  a2: -1.1519  # Middle of range [-2.30383, 0]
  a3: 0.0
  a4: 0.0
  bg: 0.0
  g1: 0.0