/bond_disable_heartbeat_timeout: true
alpha1: 0.2
alpha2: 0.2
alpha3: 0.2
alpha4: 0.2
alpha5: 0.2
always_reset_initial_pose: false
base_frame_id: base_link
beam_skip_distance: 0.5
beam_skip_error_threshold: 0.9
beam_skip_threshold: 0.3
do_beamskip: true
first_map_only: false
global_frame_id: map
initial_pose.x: 0.0
initial_pose.y: 0.0
initial_pose.yaw: 0.0
initial_pose.z: 0.0
lambda_short: 0.1
laser_likelihood_max_dist: 2.0
laser_max_range: 100.0
laser_min_range: 0.1
laser_model_type: likelihood_field
map_topic: /map
max_beams: 60
max_particles: 1000
min_particles: 300
odom_frame_id: odom
pf_err: 0.05
pf_z: 0.99
qos_overrides./tf.publisher.depth: 100
qos_overrides./tf.publisher.durability: volatile
qos_overrides./tf.publisher.history: keep_last
qos_overrides./tf.publisher.reliability: reliable
recovery_alpha_fast: 0.0
recovery_alpha_slow: 0.0
resample_interval: 2
robot_model_type: nav2_amcl::omnidirectional
save_pose_rate: 0.5
scan_topic: /scan
set_initial_pose: true
sigma_hit: 0.2
tf_broadcast: true
transform_tolerance: 0.3
update_min_a: 0.5
update_min_d: 0.5
use_sim_time: false
z_hit: 0.5
z_max: 0.05
z_rand: 0.5
z_short: 0.05
