amcl:
  ros__parameters:
    min_particles: 500
    max_particles: 5000
    kld_err: 0.05
    kld_z: 0.99
    odom_model_type: "diff-corrected"
    odom_alpha1: 0.2
    odom_alpha2: 0.2
    odom_alpha3: 0.2
    odom_alpha4: 0.2
    odom_frame_id: "odom"
    base_frame_id: "base_link"
    global_frame_id: "map"
    laser_model_type: "likelihood_field"
    laser_likelihood_max_dist: 2.0
    laser_max_range: 12.0
    laser_min_range: 0.1
    laser_max_beams: 60
    initial_pose_x: 0.0
    initial_pose_y: 0.0
    initial_pose_a: 0.0
    initial_cov_xx: 0.25
    initial_cov_yy: 0.25
    initial_cov_aa: 0.0685
    tf_broadcast: true
    transform_tolerance: 0.1
    recovery_alpha_slow: 0.0
    recovery_alpha_fast: 0.0
    use_map_topic: true