# Referee Box Configuration

# Game Parameters
game:
  match_duration: 300  # seconds
  preparation_time: 60  # seconds
  minimum_robots: 1
  maximum_robots: 4

# Scoring Parameters
scoring:
  base_points:
    task_completion: 10
    efficiency_bonus: 5
    precision_bonus: 3
  penalties:
    collision: -5
    boundary_violation: -3
    timeout: -2

# Safety Parameters
safety:
  workspace_boundaries:
    x_min: -5.0
    x_max: 5.0
    y_min: -5.0
    y_max: 5.0
  collision_threshold: 0.5  # meters
  emergency_stop_timeout: 2.0  # seconds

# Communication Parameters
communication:
  tcp_port: 5000
  ip_address: "192.168.1.100"  # Fixed IP address for referee box
  heartbeat_interval: 1.0  # seconds
  connection_timeout: 5.0  # seconds
  max_connections: 5  # Maximum number of simultaneous robot connections

# Logging Parameters
logging:
  level: INFO
  file_path: "/var/log/referee_box.log"
  max_file_size: 10485760  # 10MB
  backup_count: 5 