amcl:
  ros__parameters:
    # Motion model configuration (fixed)
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    
    # Motion model noise parameters
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    
    # Frame IDs
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    global_frame_id: "map"
    
    # Laser parameters
    laser_model_type: "likelihood_field"
    scan_topic: "/scan"
    laser_min_range: 0.1
    laser_max_range: 100.0
    laser_max_beams: 30
    laser_likelihood_max_dist: 2.0
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: true
    
    # Particle filter settings
    min_particles: 300
    max_particles: 1000
    pf_err: 0.05
    pf_z: 0.99
    resample_interval: 2
    
    # Initial pose
    initial_pose_x: 0.0
    initial_pose_y: 0.0
    initial_pose_a: 0.0
    yaw: 0.0
    set_initial_pose: true
    
    # Recovery behaviors
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    
    # Other parameters
    lambda_short: 0.1
    sigma_hit: 0.2
    transform_tolerance: 1.0
    update_min_a: 0.5
    update_min_d: 0.5
    save_pose_rate: 0.5
    tf_broadcast: true
    
    # Sensor model probabilities
    z_hit: 0.5
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.05